name: Automatic Rebase onto all branches

on:
  push:
    branches:
      - main
jobs:
  rebaseDeveloper:
    if: github.branch != 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3
      - name: ReSync Branch Developer
        uses: Joao208/resync-branch@1.5.0
        with:
          PERSONAL_TOKEN: ${{secrets.PERSONAL_TOKEN}}
          BRANCH_NAME: Developer
          DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
  rebaseDevOps:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3
      - name: ReSync Branch DevOps
        uses: Joao208/resync-branch@1.5.0
        with:
          PERSONAL_TOKEN: ${{secrets.PERSONAL_TOKEN}}
          BRANCH_NAME: Devops
          DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
  rebaseNetwork:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3
      - name: ReSync Branch Network
        uses: Joao208/resync-branch@1.5.0
        with:
          PERSONAL_TOKEN: ${{secrets.PERSONAL_TOKEN}}
          BRANCH_NAME: Network
          DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
